### ISSUE TITLE
"Flow failure" is silent

### ISSUE THREAD

**Issue by Feodor0090** [maholator/MahoTrans#19]
#18 failure is happening at link time, when it is trying to recalculate jump offset and sees that it jumps to nowhere. It fails on expected path (there is `error` opcode emited), but Shinonov implies that there was no linker message and it failed silently.

**Comment by bibarub** [comment]
@Feodor0090 who's shinonov

**Comment by Feodor0090** [comment]
@bibarub

**Comment by Feodor0090** [comment]
Well, it was not silent. Improved logs around it a bit.
